### ISSUE TITLE
System.ArgumentNullException: The GraphicsDevice must not be null when creating new resources. Crash :/

### ISSUE THREAD

**Issue by xg787** [ProjectStarlight/StarlightRiver#118]
System.ArgumentNullException: The GraphicsDevice must not be null when creating new resources.
Parameter name: graphicsDevice
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height)
   at StarlightRiver.Content.CustomHooks.PlayerTarget.Load() in StarlightRiver\Content\CustomHooks\Visuals.PlayerTarget.cs:line 31
   at StarlightRiver.StarlightRiver.Load() in StarlightRiver.cs:line 100
   at Terraria.ModLoader.ModContent.<>c.<Load>b__38_0(Mod mod)
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction)
   at Terraria.ModLoader.ModContent.Load(CancellationToken token)
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token)

**Comment by ScalarVector1** [comment]
Please re-submit this following the proper issue format and including full log files
