### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by InsomniaHUDenjoyerTF2** [ProjectStarlight/StarlightRiver#574]
Github issues should match the following format, for ease of organization and readability.

## Death Saxophone doens't activate when charged

	Normally supposed to let out a high damage attack
	Doesn't do anything when charged up
	Just crafted it and was excited to try it out, first went to a sky island and then to an underground desert because there are more enemies
	Game didn't crash/show error message

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list:
                Recipe Browser v0.10.1.2
                Wing Slot Extra v1.3.6
                Starlight River v0.1.8
                Boss checklist v1.6.1 

		Config settings: Default
		
                Game settings (only video settings): 
                
                Fullscreen 1920x1080p
                Frame Skip on
                Lighting: Retro
                Quality: Low
                Background: Off
                Gore: Off
                Heat Distort: Off
                Storm FX: Disabled
                Wave Qual: Low
                Windy enviroment: Disabled
                
                Gameplay events happening: Not Mining, Not fighting any bosses, just strolling around
		Your inputs: Left Click + movement keys
		OS: Windows 10 ver 22H2 build 19045.3086

## Additional context and log files
**Add any other context about the problem here.**
A quick dump of the client log because the template asked to put it in my bug report:

[13:28:19] [1/INFO] [tML]: Starting tModLoader v0.11.8.9 Windows client (17/08/2022)
[13:28:19] [1/INFO] [tML]: Running on NetFramework 4.8
[13:28:19] [1/INFO] [tML]: Executable: C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.exe
[13:28:19] [1/INFO] [tML]: Working Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoader
[13:28:19] [1/INFO] [tML]: Launch Parameters: 
[13:28:19] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[13:28:19] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[13:28:19] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[13:28:21] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[13:28:21] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[13:28:23] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[13:28:23] [1/INFO] [tML]: Checking Steam installation...
[13:28:24] [1/INFO] [tML]: Steam installation OK.
[13:28:24] [1/INFO] [Terraria]: Found Terraria steamapp install at: C:\Program Files (x86)\Steam\steamapps\common\Terraria
[13:28:24] [1/INFO] [Terraria]: Steam Cloud Quota: 125.2 MB available
[13:28:28] [1/DEBUG] [Terraria]: Graphics Device: Intel(R) UHD Graphics {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
[13:28:28] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach -> HiDef, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[13:28:33] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[13:28:35] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[13:28:36] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[13:28:38] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[13:28:39] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[13:28:44] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800 -> 1920, Height: 480 -> 1080, Fullscreen: False, Display: \\.\DISPLAY1
[13:28:48] [11/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[13:28:49] [11/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[13:28:50] [8/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[13:28:51] [8/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[13:28:53] [7/INFO] [Terraria]: JIT loading finished
[13:28:53] [8/INFO] [tML]: Unloading mods
[13:28:55] [8/INFO] [tML]: Finding Mods...
[13:29:04] [8/INFO] [tML]: Sandboxing: CalamityMod
[13:29:12] [8/INFO] [tML]: Sandboxing: CalamityModMusic
[13:29:13] [8/INFO] [tML]: Sandboxing: AlchemistNPCLite
[13:29:16] [8/INFO] [tML]: Sandboxing: BossChecklist
[13:29:16] [8/INFO] [tML]: Sandboxing: BothEvils
[13:29:17] [8/INFO] [tML]: Sandboxing: CalamityBloodwormMod
[13:29:17] [8/INFO] [tML]: Sandboxing: ClamExtraMusic
[13:29:17] [8/INFO] [tML]: Sandboxing: Luiafk
[13:29:18] [8/INFO] [tML]: Sandboxing: MagicStorage
[13:29:18] [8/INFO] [tML]: Sandboxing: MagicStorageExtra
[13:29:19] [8/INFO] [tML]: Sandboxing: OmniSwing
[13:29:19] [8/INFO] [tML]: Sandboxing: RecipeBrowser
[13:29:20] [8/INFO] [tML]: Sandboxing: VeinMiner
[13:29:20] [8/INFO] [tML]: Sandboxing: WeaponOut
[13:29:21] [8/INFO] [tML]: Instantiating Mods...
[13:29:25] [8/INFO] [tML]: Initializing: ModLoader (tModLoader) v0.11.8.9
[13:29:27] [8/INFO] [tML]: Initializing: CalamityMod (Calamity Mod (No Calamity Music)) v1.5.1.6
[13:29:52] [8/DEBUG] [tML]: Assembly Resolve: CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[13:29:53] [8/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[13:29:53] [8/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=19.12.19.1 -> 20.11.16.1
[13:29:53] [8/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[13:29:53] [8/WARN] [tML]: Upgraded Reference MonoMod.RuntimeDetour -> Version=19.12.19.1 -> 20.11.16.1
[13:29:53] [8/DEBUG] [tML]: Hook On.Terraria.NPC::ApplyTileCollision(bool, Vector2, int, int) added by CalamityMod_0
[13:29:53] [8/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod_0
[13:29:54] [8/DEBUG] [tML]: Hook On.Terraria.Main::UpdateTime_SpawnTownNPCs() added by CalamityMod_0
[13:29:54] [8/DEBUG] [tML]: Hook IL.Terraria.Player::Hurt(PlayerDeathReason, int, int, bool, bool, bool, int) modified by CalamityMod_0
[13:29:54] [8/DEBUG] [tML]: Hook IL.Terraria.Player::DashMovement() modified by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook IL.Terraria.Player::Update_NPCCollision() modified by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook On.Terraria.WorldGen::OpenDoor(int, int, int) added by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook On.Terraria.WorldGen::CloseDoor(int, int, bool) added by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook On.Terraria.Wiring::Teleport() added by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook IL.Terraria.Main::DrawInterface_40_InteractItemIcon() modified by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook On.Terraria.Item::AffixName() added by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook On.Terraria.Projectile::NewProjectile(float, float, float, float, int, int, float, int, float, float) added by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook On.Terraria.Main::DrawCursor(Vector2, bool) added by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook IL.Terraria.Player::QuickHeal() modified by CalamityMod_0
[13:29:55] [8/DEBUG] [tML]: Hook IL.Terraria.Player::QuickMana() modified by CalamityMod_0
[13:29:56] [8/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck(int) modified by CalamityMod_0
[13:30:00] [8/DEBUG] [tML]: Hook IL.Terraria.Player::AddBuff(int, int, bool) modified by CalamityMod_0
[13:30:00] [8/DEBUG] [tML]: Hook On.Terraria.Main::DrawInterface(GameTime) added by CalamityMod_0
[13:30:00] [8/DEBUG] [tML]: Hook On.Terraria.Main::SortDrawCacheWorms() added by CalamityMod_0
[13:30:00] [8/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by CalamityMod_0
[13:30:01] [8/DEBUG] [tML]: Hook IL.Terraria.Main::DrawTiles(bool, int) modified by CalamityMod_0
[13:30:08] [8/DEBUG] [tML]: Hook IL.Terraria.GameContent.Liquid.LiquidRenderer::InternalDraw(SpriteBatch, Vector2, int, float, bool) modified by CalamityMod_0
[13:30:08] [8/DEBUG] [tML]: Hook IL.Terraria.Main::oldDrawWater(bool, int, float) modified by CalamityMod_0
[13:30:09] [8/DEBUG] [tML]: Hook IL.Terraria.WaterfallManager::DrawWaterfall(SpriteBatch, int, float) modified by CalamityMod_0
[13:30:10] [8/DEBUG] [tML]: Hook On.Terraria.NPC::Collision_DecideFallThroughPlatforms() added by CalamityMod_0
[13:30:10] [8/DEBUG] [tML]: Hook IL.Terraria.Wiring::HitWireSingle(int, int) modified by CalamityMod_0
[13:30:10] [8/DEBUG] [tML]: Hook IL.Terraria.Main::DamageVar(float) modified by CalamityMod_0
[13:30:10] [8/DEBUG] [tML]: Hook IL.Terraria.NPC::scaleStats() modified by CalamityMod_0
[13:30:11] [8/DEBUG] [tML]: Hook IL.Terraria.Projectile::AI_001() modified by CalamityMod_0
[13:30:14] [8/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateJumpHeight() modified by CalamityMod_0
[13:30:14] [8/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[13:30:16] [8/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[13:30:18] [8/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[13:30:20] [8/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[13:30:22] [8/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[13:30:24] [8/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateManaRegen() modified by CalamityMod_0
[13:30:24] [8/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Pyramid(int, int) modified by CalamityMod_0
[13:30:24] [8/DEBUG] [tML]: Hook IL.Terraria.WorldGen::MakeDungeon(int, int) modified by CalamityMod_0
[13:30:24] [8/DEBUG] [tML]: Hook IL.Terraria.WorldGen::DungeonHalls(int, int, ushort, int, bool) modified by CalamityMod_0
[13:30:24] [8/DEBUG] [tML]: Hook IL.Terraria.WorldGen::GrowLivingTree(int, int) modified by CalamityMod_0
[13:30:25] [8/DEBUG] [tML]: Hook On.Terraria.WorldGen::SmashAltar(int, int) added by CalamityMod_0
[13:30:25] [8/DEBUG] [tML]: Hook IL.Terraria.WorldGen::hardUpdateWorld(int, int) modified by CalamityMod_0
[13:30:25] [8/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Chlorophyte(int, int) modified by CalamityMod_0
[13:30:25] [8/DEBUG] [tML]: Hook IL.Terraria.Item::Prefix(int) modified by CalamityMod_0
[13:30:25] [8/DEBUG] [tML]: Hook On.Terraria.NPC::SlimeRainSpawns(int) added by CalamityMod_0
[13:30:25] [8/DEBUG] [tML]: Hook IL.Terraria.NPC::SpawnNPC() modified by CalamityMod_0
[13:30:27] [8/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod_0
[13:30:27] [8/DEBUG] [tML]: Hook On.Terraria.Main::InitLifeBytes() added by CalamityMod_0
[13:30:27] [8/DEBUG] [tML]: Hook IL.Terraria.NPC::NPCLoot() modified by CalamityMod_0
[13:30:32] [8/INFO] [tML]: Initializing: CalamityModMusic (Calamity Mod Music) v1.5.1.1
[13:30:32] [8/INFO] [tML]: Initializing: AlchemistNPCLite (AlchemistNPC Lite) v1.8.10
[13:30:32] [8/INFO] [tML]: Initializing: BossChecklist (Boss Checklist) v1.1.6.1
[13:30:33] [8/DEBUG] [tML]: Hook On.Terraria.GameContent.Events.DD2Event::WinInvasionInternal() added by BossChecklist_0
[13:30:33] [8/INFO] [BossChecklist]: Boss Log integration messages will not be logged.
[13:30:33] [8/INFO] [tML]: Initializing: BothEvils (Fargo's Both Evils) v3.1
[13:30:33] [8/INFO] [tML]: Initializing: CalamityBloodwormMod (Calamity Bloodworm Recipe) v1.0.0.2
[13:30:33] [8/INFO] [tML]: Initializing: ClamExtraMusic (Calamity Mod Extra Music) v1.0.7.5
[13:30:34] [8/INFO] [tML]: Initializing: Luiafk (Luiafk) v1.0.0.130
[13:30:34] [8/INFO] [tML]: Initializing: MagicStorage (Magic Storage) v0.4.3.6
[13:30:34] [8/DEBUG] [tML]: Hook On.Terraria.NetMessage::SendData(int, int, int, NetworkText, int, float, float, float, int, int, int) added by MagicStorage_0
[13:30:35] [8/DEBUG] [tML]: Hook On.Terraria.MessageBuffer::GetData(int, int, out int) added by MagicStorage_0
[13:30:36] [8/INFO] [tML]: Initializing: MagicStorageExtra (Magic Storage - Extra) v0.5.5.10
[13:30:36] [8/DEBUG] [tML]: Hook On.Terraria.NetMessage::SendData(int, int, int, NetworkText, int, float, float, float, int, int, int) added by MagicStorageExtra_0
[13:30:36] [8/DEBUG] [tML]: Hook On.Terraria.MessageBuffer::GetData(int, int, out int) added by MagicStorageExtra_0
[13:30:36] [8/INFO] [tML]: Initializing: OmniSwing (OmniSwing) v3.0.1
[13:30:36] [8/INFO] [tML]: Initializing: RecipeBrowser (Recipe Browser) v0.8.9.1
[13:30:36] [8/DEBUG] [tML]: Hook On.Terraria.Recipe::FindRecipes() added by RecipeBrowser_0
[13:30:36] [1/WARN] [tML]: Silently Caught Exception: 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Terraria.ModLoader.ModHotKey.GetAssignedKeys(InputMode mode)
   at MagicStorageExtra.CraftingGUI.Update(GameTime gameTime) in MagicStorageExtra\CraftingGUI.cs:line 414
   at MagicStorageExtra.MagicStorageExtra.PostUpdateInput() in MagicStorageExtra.cs:line 97
   at Terraria.ModLoader.ModHooks.PostUpdateInput()
   at Terraria.Main.DoUpdate_HandleInput()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[13:30:36] [8/DEBUG] [tML]: Hook On.Terraria.Player::AdjTiles() added by RecipeBrowser_0
[13:30:37] [8/INFO] [tML]: Initializing: VeinMiner (VeinMiner) v1.3.1
[13:30:37] [8/DEBUG] [tML]: Web Request: http://textuploader.com/dhrr7/raw
[13:30:37] [8/DEBUG] [tML]: Web Request: https://textuploader.com/dhrr7/raw
[13:30:38] [8/WARN] [tML]: Silently Caught Exception: 
System.Net.WebException: De externe server heeft een fout geretourneerd: (503) Server is niet beschikbaar.
   bij System.Net.HttpWebRequest.GetResponse()
   bij System.Net.WebClient.GetWebResponse(WebRequest request)
   bij System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream, CompletionDelegate completionDelegate, AsyncOperation asyncOp)
   bij System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bij System.Net.WebClient.DownloadString(Uri address)
   bij System.Net.WebClient.DownloadString(String address)
   bij VeinMiner.ModOres.DownloadOreList()
   bij VeinMiner.VeinMiner.Load()
   bij Terraria.ModLoader.ModContent.<>c.<Load>b__38_0(Mod mod)
   bij Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction)
   bij Terraria.ModLoader.ModContent.Load(CancellationToken token)
   bij Terraria.ModLoader.ModLoader.Load(CancellationToken token)
   bij Terraria.ModLoader.ModLoader.<>c__DisplayClass42_0.<BeginLoad>b__0()
   bij System.Threading.Tasks.Task.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
   bij System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   bij System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   bij System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   bij System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bij System.Threading.ThreadPoolWorkQueue.Dispatch()
   bij System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[13:30:38] [8/INFO] [VeinMiner]: VeinMiner: Couldn't access online ore list, reading from file.
[13:30:38] [8/INFO] [VeinMiner]:    bij System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bij System.Net.WebClient.DownloadString(Uri address)
   bij System.Net.WebClient.DownloadString(String address)
   bij VeinMiner.ModOres.DownloadOreList()
[13:30:38] [8/WARN] [tML]: Silently Caught Exception: 
System.IO.FileNotFoundException: Kan bestand C:\Users\Jeffr\Documents\My Games\Terraria\ModLoader\VeinMinerDownloadedOreList niet vinden.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bij VeinMiner.ModOres.DownloadOreList()
   bij VeinMiner.VeinMiner.Load()
   bij Terraria.ModLoader.ModContent.<>c.<Load>b__38_0(Mod mod)
   bij Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction)
   bij Terraria.ModLoader.ModContent.Load(CancellationToken token)
   bij Terraria.ModLoader.ModLoader.Load(CancellationToken token)
   bij Terraria.ModLoader.ModLoader.<>c__DisplayClass42_0.<BeginLoad>b__0()
   bij System.Threading.Tasks.Task.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
   bij System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   bij System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   bij System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   bij System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bij System.Threading.ThreadPoolWorkQueue.Dispatch()
   bij System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[13:30:38] [8/INFO] [VeinMiner]: VeinMiner: Couldn't access saved ore list file, using a backup list embedded into the mod.
[13:30:38] [8/INFO] [VeinMiner]:    bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bij VeinMiner.ModOres.DownloadOreList()
[13:30:38] [8/INFO] [tML]: Initializing: WeaponOut (WeaponOut) v1.6.4
[13:30:39] [8/INFO] [tML]: Setting up...
[13:30:40] [8/INFO] [tML]: Loading: ModLoader (tModLoader) v0.11.8.9
[13:30:40] [8/INFO] [tML]: Loading: CalamityMod (Calamity Mod (No Calamity Music)) v1.5.1.6
[13:30:45] [8/INFO] [CalamityMod]: ModLoader version > 0.11.7.7 detected. Mechworm UUID workaround is disabled.
[13:30:46] [8/INFO] [tML]: Loading: CalamityModMusic (Calamity Mod Music) v1.5.1.1
[13:30:46] [8/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[13:30:47] [8/INFO] [tML]: Loading: AlchemistNPCLite (AlchemistNPC Lite) v1.8.10
[13:30:47] [8/INFO] [tML]: Loading: BossChecklist (Boss Checklist) v1.1.6.1
[13:30:48] [8/INFO] [tML]: Loading: BothEvils (Fargo's Both Evils) v3.1
[13:30:48] [8/INFO] [tML]: Loading: CalamityBloodwormMod (Calamity Bloodworm Recipe) v1.0.0.2
[13:30:48] [8/INFO] [tML]: Loading: ClamExtraMusic (Calamity Mod Extra Music) v1.0.7.5
[13:30:48] [8/INFO] [tML]: Loading: Luiafk (Luiafk) v1.0.0.130
[13:30:49] [8/INFO] [tML]: Loading: MagicStorage (Magic Storage) v0.4.3.6
[13:30:49] [8/INFO] [tML]: Loading: MagicStorageExtra (Magic Storage - Extra) v0.5.5.10
[13:30:49] [8/INFO] [tML]: Loading: OmniSwing (OmniSwing) v3.0.1
[13:30:49] [8/INFO] [tML]: Loading: RecipeBrowser (Recipe Browser) v0.8.9.1
[13:30:49] [8/INFO] [tML]: Loading: VeinMiner (VeinMiner) v1.3.1
[13:30:50] [8/INFO] [tML]: Loading: WeaponOut (WeaponOut) v1.6.4
[13:30:50] [8/INFO] [tML]: RAM usage: 2,1 GB
[13:30:51] [8/INFO] [tML]: Adding Recipes...
[13:30:54] [8/DEBUG] [tML]: Assembly Resolve:  -> RecipeBrowser_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[13:30:54] [8/DEBUG] [tML]: Assembly Resolve:  -> RecipeBrowser_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[13:32:10] [8/INFO] [Terraria]: Loading World: I need a lemon, IsCloud=True
[13:32:10] [8/INFO] [StatusText]: Resetting game objects
[13:32:17] [8/INFO] [StatusText]: Loading world data
[13:32:18] [8/INFO] [StatusText]: Settling liquids
[13:32:30] [8/INFO] [StatusText]: Loading map data
[13:32:33] [8/INFO] [StatusText]: Drawing map
[13:32:35] [1/INFO] [Terraria]: Entering world with player: Gandalfpotter, IsCloud=True
[13:33:02] [1/DEBUG] [tML]: Assembly Resolve: AlchemistNPCLite_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[13:36:20] [1/INFO] [Terraria]: Loaded 6000 vanilla assets
[13:42:38] [11/INFO] [StatusText]: Saving world data
[13:42:42] [11/INFO] [StatusText]: Validating world save
[13:46:10] [1/INFO] [Terraria]: Loaded 7000 vanilla assets
[13:52:37] [7/INFO] [StatusText]: Saving world data
[13:52:41] [7/INFO] [StatusText]: Validating world save
[14:02:37] [16/INFO] [StatusText]: Saving world data
[14:02:42] [16/INFO] [StatusText]: Validating world save
[14:03:19] [1/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[14:03:19] [20/INFO] [StatusText]: Saving map data
[14:03:26] [20/INFO] [StatusText]: Saving world data
[14:03:28] [20/INFO] [StatusText]: Validating world save
[14:03:38] [33/INFO] [Terraria]: Loading World: I need a lemon, IsCloud=True
[14:03:39] [33/INFO] [StatusText]: Resetting game objects
[14:03:40] [33/INFO] [StatusText]: Loading world data
[14:03:41] [33/INFO] [StatusText]: Settling liquids
[14:03:49] [33/INFO] [StatusText]: Loading map data
[14:03:52] [33/INFO] [StatusText]: Drawing map
[14:03:52] [1/INFO] [Terraria]: Entering world with player: Gandalfpotter, IsCloud=True
[14:05:35] [1/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateAudio() modified by CalamityModMusic_0
[14:05:35] [21/INFO] [StatusText]: Saving map data
[14:05:41] [21/INFO] [StatusText]: Saving world data
[14:05:43] [21/INFO] [StatusText]: Validating world save
[14:17:17] [32/INFO] [StatusText]: Resetting game objects
[14:17:17] [32/INFO] [Terraria]: Generating World: try not to smash pc
[14:18:29] [32/INFO] [StatusText]: Creating underworld
[14:18:38] [32/INFO] [StatusText]: Creating dungeon
[14:18:59] [32/INFO] [StatusText]: Settling liquids
[14:20:50] [32/INFO] [StatusText]: Saving world data
[14:20:51] [32/INFO] [StatusText]: Validating world save

**Comment by TripleFate** [comment]
Make sure its actually fully charged for this bug report. it takes you getting hit >30 times or hitting enemies >90 times for the effect to be activated. DoT effects do not contribute towards charging.
