### ISSUE TITLE
[Minor Bug] Item Deserialization Fail Causes World to not Load with Magic Storage

### ISSUE THREAD

**Issue by absoluteAquarian** [ProjectStarlight/StarlightRiver#690]
## Issue Description
Recently, a user reported a "Load failed!" error in the _absoluteAquarian Mods_ Discord server.  Included within their log file was the following error:
```yaml
[20:23:20.342] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.IO.IOException: NBT Deserialization (type=System.Int32,entry=float "FullnessMult" = 1)
   at Terraria.ModLoader.IO.TagCompound.TryGet[T](String key, T& value) in tModLoader\Terraria\ModLoader\IO\TagCompound.cs:line 47
   at Terraria.ModLoader.IO.TagCompound.Get[T](String key) in tModLoader\Terraria\ModLoader\IO\TagCompound.cs:line 23
   at StarlightRiver.Content.Items.Food.Meal.LoadData(TagCompound tag) in StarlightRiver\Content\Items\Food\Meal.cs:line 135
   at Terraria.ModLoader.IO.ItemIO.Load(Item item, TagCompound tag) in tModLoader\Terraria\ModLoader\IO\ItemIO.cs:line 93
   at Terraria.ModLoader.IO.ItemIO.Load(TagCompound tag) in tModLoader\Terraria\ModLoader\IO\ItemIO.cs:line 119
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at MagicStorage.Components.TEStorageUnit.LoadData(TagCompound tag) in MagicStorage\Components\TEStorageUnit.cs:line 455
```

The full client log can be found [here](https://hst.sh/azolekovef.yaml).

**Comment by ScalarVector1** [comment]
This user is using an incredibly outdated version of the mod. Please direct them to update from the workshop.
