### ISSUE TITLE
Unable to host a multiplayer world after update to v0.2.7

### ISSUE THREAD

**Issue by AshlyneS** [ProjectStarlight/StarlightRiver#713]
After the update to v0.2.7 I am unable to host a multiplayer server because TModloader does not allow it to load due to a version issue.

## Issue Description
**A thorough description of the problem, including:**
	**Expected behavior:** Mod to load
	**Actual behavior:** Does not load
	**Context:** This happened after the update to v0.2.7
	**Error message (if applicable):** 
``` [12:15:15.601] [Main Thread/ERROR] [tML]: An error occurred while loading StarlightRiver v0.2.7
It has been detected that this mod was built for tModLoader v2023.12.3.1
However, you are using tModLoader v2024.3.3.2
The mod(s) have been automatically disabled.
This error was caused by the "StarlightRiver.Content.Bosses.SquidBoss.ArenaActor" class.
System.NullReferenceException: Object reference not set to an instance of an object.
   at AdvancedWorldGen.SpecialOptions.Halloween.HalloweenCommon.HalloweenSwap(orig_SetDefaults orig, NPC self, Int32 type, NPCSpawnParams spawnParams) in AdvancedWorldGen\SpecialOptions\Halloween\HalloweenCommon.cs:line 27
   at Hook<System.Void AdvancedWorldGen.SpecialOptions.Halloween.HalloweenCommon::HalloweenSwap(Terraria.On_NPC+orig_SetDefaults,Terraria.NPC,System.Int32,Terraria.NPCSpawnParams)>(NPC , Int32 , NPCSpawnParams )
   at SyncProxy<System.Void Terraria.NPC:SetDefaults(System.Int32, Terraria.NPCSpawnParams)>(NPC , Int32 , NPCSpawnParams )
   at Terraria.NPC.SetDefaults(Int32 Type, NPCSpawnParams spawnparams)
   at StarlightRiver.Content.Bosses.SquidBoss.ArenaActor.SetDefaults() in StarlightRiver\Content\Bosses\SquidBoss\NPCs.ArenaActor.cs:line 59
   at Terraria.ModLoader.Core.GlobalLoaderUtils`2.SetDefaultsBeforeLookupsAreBuilt(TEntity entity, TGlobal[] entityGlobals, Action`1 setModEntityDefaults, InstantiationTime[]& instTimes) in tModLoader\Terraria\ModLoader\Core\GlobalLoaderUtils.cs:line 84
   at Terraria.ModLoader.Core.GlobalLoaderUtils`2.SetDefaultsBeforeLookupsAreBuilt(TEntity entity, TGlobal[] entityGlobals, Action`1 setModEntityDefaults) in tModLoader\Terraria\ModLoader\Core\GlobalLoaderUtils.cs:line 63
   at Terraria.ModLoader.Core.GlobalLoaderUtils`2.SetDefaults(TEntity entity, TGlobal[]& entityGlobals, Action`1 setModEntityDefaults) in tModLoader\Terraria\ModLoader\Core\GlobalLoaderUtils.cs:line 29
   at Terraria.ModLoader.ModNPC.SetupContent() in tModLoader\Terraria\ModLoader\ModNPC.cs:line 116
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 129
--- End of stack trace from previous location ---
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 137
   at Terraria.ModLoader.Mod.SetupContent() in tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 25
   at Terraria.ModLoader.ModContent.<>c.<Load>b__44_1(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 324
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 408
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 323
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 132
```

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
                **TModloader Version:** v2024.3.3.2
		**Mod list:** [enabled.json](https://github.com/ProjectStarlight/StarlightRiver/files/15213855/enabled.json) [install.txt](https://github.com/ProjectStarlight/StarlightRiver/files/15213856/install.txt)
		**Config settings:** Default
		**Game settings:** [config.json](https://github.com/ProjectStarlight/StarlightRiver/files/15213864/config.json)
		**Gameplay events happening:** Loading into a multiplayer world
		**Your inputs:** Loading into a world
		**OS:** Windows 11 Version	10.0.22631 Build 22631

## Additional context and log files
**Add any other context about the problem here.** 
This <ins>only</ins> happens when hosting multiplayer. 
**Fixes I have tried (in order):** 
1. unsubscribed and resubscribed
2. reinstalled tmodloader and terraria
3. tried making a new character and multiplayer world
4. validating files
5. deleting old versions of the mod in the workshop folder so only the latest is left which is apparently 2023.12 (This doesn't seem like it should be the latest? Is workshop just not downloading the new version?)

**Logs:** [server.log](https://github.com/ProjectStarlight/StarlightRiver/files/15213878/server.log)

**Comment by AshlyneS** [comment]
Update: i have even tried on a different computer. Same issue

**Comment by ScalarVector1** [comment]
This appears to be a cross-mod incompatability. I'll keep this open to investigate further but it appears to have something to do with creating the fake NPC for auroracle's arena during SetDefaults. Perhaps I need to prevent this from running on the server.
